- name: Install and configure Jupyter-lab-extension
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Gather facts for first time
      setup:

    - name: Ubuntu
      when: ansible_distribution == 'Ubuntu'
      block:
      - name: Update nodejs ppa installer
        get_url:
          url: https://deb.nodesource.com/setup_14.x
          dest: /tmp/nodejs-installer.sh
          mode: 0755

      - name: Execute nodejs ppa installer
        command: /tmp/nodejs-installer.sh

      - name: Remove nodejs ppa installer
        file:
          path: /tmp/nodejs-installer.sh
          state: absent

      - name: Install NodeJS
        apt:
          name: "{{ packages }}"
          allow_unauthenticated: yes
        vars:
          packages:
          - nodejs
      - name: Ensure python 3 packages for Jupyter are installed
        pip:
          name: "{{ packages }}"
          executable: pip3
        vars:
          packages:
          - jupyterlab==3.0.10
          - jupyter-packaging
          - jupyterlab-git
          - jupyterlab-system-monitor
          - jupyterlab-lsp
          - python-language-server[all]
          - ipywidgets
          - tqdm
          - antspyx
          - wget
          - simpleitk
          - numpy
          - pandas
          - arviz
          - matplotlib
          - cmdstanpy
          - xnat
      - name: Execute jupyterlab build
        command: jupyter lab build
      - name: Reload jupyterhub service
        systemd:
          state: restarted
          daemon_reload: yes
          name: jupyterhub

      - name: Ensure Jupyterhub is started
        register: start_jupyterhub
        service:
          name: jupyterhub
          state: restarted
          enabled: yes

      - debug:
          msg: 'service_url: {"url": "https://{{ ansible_host }}", "tag": "web", "description": "Jupyter"}'
        when: (start_jupyterhub is succeeded)
