- name: Install and configure Jupyter
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Download nodejs ppa installer
      get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: /tmp/nodejs-installer.sh
        mode: 0755

    - name: Execute nodejs ppa installer
      command: /tmp/nodejs-installer.sh

    - name: Remove nodejs ppa installer
      file:
        path: /tmp/nodejs-installer.sh
        state: absent

    - name: update nodejs
      command: apt-get update && apt-get install nodejs --upgrade
    - name: update pip
      command: pip3 install pip --upgrade
    - name: Install python 3 packages for Jupyter are installed
      command: pip3 install jupyterlab==2.2.0 jupyterhub jupyterlab-git jupyterlab-system-monitor jupyterlab-lsp sqlalchemy flask-sqlalchemy python-language-server[all] lckr-jupyterlab-variableinspector ipywidgets tqdm antspyx wget simpleitk numpy pandas arviz matplotlib xnat virtualenv --upgrade --use-deprecated=legacy-resolver

    - name: Execute jupyterlab update
      command: jupyter labextension update --all
    - name: Execute jupyterlab build
      command: jupyter lab build

    - name: Reload jupyterhub service
      systemd:
        state: restarted
        daemon_reload: yes
        name: jupyterhub

    - name: Ensure Jupyterhub is started
      register: start_jupyterhub
      service:
        name: jupyterhub
        state: restarted
        enabled: yes

    - debug:
        msg: 'service_url: {"url": "https://{{ ansible_host }}", "tag": "web", "description": "Jupyter"}'
      when: (start_jupyterhub is succeeded)
