- name: Install and configure Jupyter-lab-extension
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Update nodejs ppa installer
      get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: /tmp/nodejs-installer.sh
        mode: 0755

    - name: Execute nodejs ppa installer
      command: /tmp/nodejs-installer.sh

    - name: Remove nodejs ppa installer
      file:
        path: /tmp/nodejs-installer.sh
        state: absent

    - name: Install NodeJS
      apt:
        name: "{{ packages }}"
        allow_unauthenticated: yes
      vars:
        packages:
        - nodejs
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes
    - name: Ensure python 3 packages for Jupyter are installed
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
        - jupyterlab==2.2.0
        - jupyterlab-git
        - jupyterlab-system-monitor
        - jupyterlab-lsp
        - python-language-server[all]
        - ipywidgets
        - tqdm
        - antspyx
        - wget
        - simpleitk
        - numpy
        - pandas
        - arviz
        - matplotlib
        - cmdstanpy
        - xnat
    - name: Execute jupyterlab build
      command: jupyter labextension update --all
    - name: Unconditionally reboot the machine with all defaults
      reboot:
